# Задание №2

In [2]:
import sys

sys.path.append('..')

минимизировать: $$-x_1 - 2x_2$$

при условии: $$x_1 - 2x_2 \geq 2$$
             $$x_1 + x_2 \leq 4$$
             $$x_1, x_2 \geq 0$$

<center>
    <h3>Стандартная форма</h3>
</center>

минимизировать: $$-x_1 - 2x_2$$

при условии: $$x_1 - 2x_2 - x_3 = 2$$
             $$x_1 + x_2 + x_4 = 4$$
             $$x_1, x_2, x_3, x_4 \geq 0$$

<br/>             

$$
    A = \begin{pmatrix}        
        1 & -2 & -1 & 0 \\
        1 & 1 & 0 & 1 \\
    \end{pmatrix},

    b = \begin{pmatrix} 
        2 \\
        4 \\
    \end{pmatrix}
$$

Существует $C_{4}^2 = 6$ базовых допустимых решений

In [6]:
from modules.feasable_set import generate_feasable_set

A = [
    [1., 1.],
    [-2., 1.],
    [-1., 0.],
    [0., 1.]
]

b = [2., 4.]

bfs = generate_feasable_set(A, b)

bfs

[0, 1]: x = [3.33333333 0.66666667] является базовым допустим решением
---

[0, 2]: x = [4. 2.] является базовым допустим решением
---

[0, 3]: x = [2. 2.] является базовым допустим решением
---

[1, 2]: k = 1, x[k] = -10.0 отрицательна
---

[1, 3]: k = 0, x[k] = -1.0 отрицательна
---

[2, 3]: k = 0, x[k] = -2.0 отрицательна
---



[array([3.33333333, 0.66666667, 0.        , 0.        ]),
 array([4., 0., 2., 0.]),
 array([2., 0., 0., 2.])]

In [4]:
from numpy import dot, array

c = array([-1., -2., 0., 0.])

min_val = 1
x_min = None

for x in bfs:
    val = dot(c, x)

    if val < min_val:
        x_min = x
        min_val = val

print(f'Минимальное значение: {min_val}')

x_min

Минимальное значение: -4.666666666666666


array([3.33333333, 0.66666667, 0.        , 0.        ])

In [5]:
from scipy.optimize import linprog

c = [-1., -2.]

A = [
    [-1., 2.],
    [1., 1.]
]

b = [-2., 4.]

bounds = [
    [0., None],
    [0., None]
]

linprog(c, A, b, bounds=bounds)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -4.666666666666667
              x: [ 3.333e+00  6.667e-01]
            nit: 0
          lower:  residual: [ 3.333e+00  6.667e-01]
                 marginals: [ 0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf]
                 marginals: [ 0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00]
                 marginals: [-3.333e-01 -1.333e+00]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0