In [80]:
import sys

sys.path.append('..')

### Пример №2:

минимизировать: $$-x_1-2x_2$$

при условии: $$x_1 - 2x_2 \geq 2$$
             $$x_1 + x_2 \leq 4$$
             $$x_1 \geq 0$$
             $$ x_2 \geq 0$$


<br/>

<center>
    <h3>Стандартная форма</h3>
</center>

минимизировать: $$-x_1-2x_2$$

при условии: $$x_1 + x_2 - x_3 = 2$$
             $$x_1 + x_2 + x_4 = 4$$
             $$x_1 - x_5 = 0$$
             $$x_2 - x_6 = 0$$
             $$x_1, x_2, x_3, x_4, x_5 x_6 \geq 0$$

<br/>             

$$
    A = \begin{pmatrix}        
        1 & 1 & 1 & 0 & 0 & 0 \\
        1 & 1 & 0 & 1 & 0 & 0 \\
        1 & 0 & 0 & 0 & 1 & 0 \\
    \end{pmatrix},

    b = \begin{pmatrix} 
        2 \\
        4 \\
        0 \\
    \end{pmatrix}
$$
             

In [81]:
from modules.feasable_set import generate_feasable_set

A = [
    [1., 1., 1.],
    [1., 1., 0.],
    [1., 0., 0.],
    [0., 1., 0.],
    [0., 0., 1.],
    [0., 0., 0.]
]

b = [2., 4., 0.]

bfs = generate_feasable_set(A, b)

bfs

[0, 1, 2]: k = 2, x[k] = -2.0 отрицательна
---

[0, 1, 3]: x = [0. 2. 2.] является базовым допустим решением
---

[0, 1, 4]:
Матрица B = [[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 1.]] вырождена
---

[0, 1, 5]:
Матрица B = [[1. 1. 1.]
 [1. 1. 0.]
 [0. 0. 0.]] вырождена
---

[0, 2, 3]: x = [0. 2. 4.] является базовым допустим решением
---

[0, 2, 4]: k = 1, x[k] = -2.0 отрицательна
---

[0, 2, 5]:
Матрица B = [[1. 1. 1.]
 [1. 0. 0.]
 [0. 0. 0.]] вырождена
---

[0, 3, 4]: k = 2, x[k] = -2.0 отрицательна
---

[0, 3, 5]:
Матрица B = [[1. 1. 1.]
 [0. 1. 0.]
 [0. 0. 0.]] вырождена
---

[0, 4, 5]:
Матрица B = [[1. 1. 1.]
 [0. 0. 1.]
 [0. 0. 0.]] вырождена
---

[1, 2, 3]:
Матрица B = [[1. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]] вырождена
---

[1, 2, 4]: k = 1, x[k] = -2.0 отрицательна
---

[1, 2, 5]:
Матрица B = [[1. 1. 0.]
 [1. 0. 0.]
 [0. 0. 0.]] вырождена
---

[1, 3, 4]: x = [2. 2. 0.] является базовым допустим решением
---

[1, 3, 5]:
Матрица B = [[1. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]] вырождена
---

[1, 4, 5]:

[array([0., 2., 0., 2., 0., 0.]),
 array([0., 0., 2., 4., 0., 0.]),
 array([0., 2., 0., 2., 0., 0.]),
 array([0., 0., 2., 4., 0., 0.])]

In [82]:
from numpy import dot, array

c = array([0., 2., 0., 2., 0., 0.])

min_val = 1
x_min = None

for x in bfs:
    val = dot(c, x)

    if val < min_val:
        x_min = x
        min_val = val

print(f'Минимальное значение: {min_val}')

x_min

Минимальное значение: 1


In [83]:
from scipy.optimize import linprog

c = [-1., -2.]

bounds = [
    [1., 0.],
    [1., 0.]
]

linprog(c, bounds=bounds)

       message: The problem is infeasible. (HiGHS Status 8: model_status is Infeasible; primal_status is At lower/fixed bound)
       success: False
        status: 2
           fun: None
             x: None
           nit: 0
         lower:  residual: None
                marginals: None
         upper:  residual: None
                marginals: None
         eqlin:  residual: None
                marginals: None
       ineqlin:  residual: None
                marginals: None