# Нахождение базовых допустимых решений

In [3]:
import sys

sys.path.append('..')

### Пример №1

минимизировать: $$-x_1 - x_2$$

при условии: $$0 \leq x_1 \leq 1$$
             $$0 \leq x_2 \leq 1$$

<center>
    <img src="../images/feasable_set.png" width="260">
</center>

<br/>

<center>
    <h3>Стандартная форма</h3>
</center>

минимизировать: $$-x_1 - x_2$$

при условии: $$x_1 + x_3 = 1$$
             $$x_2 + x_4 = 1$$
             $$x_1, x_2, x_3, x_4 \geq 0$$

<br/>             

$$
    A = \begin{pmatrix}        
        1 & 0 & 1 & 0 \\
        0 & 1 & 0 & 1 \\
    \end{pmatrix},

    b = \begin{pmatrix} 
        1 \\
        1 \\
    \end{pmatrix}
$$

Существует $C_{4}^2 = 6$ базовых допустимых решений

In [4]:
from modules.feasable_set import generate_feasable_set

A = [
    [1., 0.],
    [0., 1.],
    [1., 0.],
    [0., 1.]
]

b = [1., 1.]

bfs = generate_feasable_set(A, b)

bfs

[0, 1]: x = [1. 1.] является базовым допустим решением
---

[0, 2]:
Матрица B = [[1. 0.]
 [1. 0.]] вырождена
---

[0, 3]: x = [1. 1.] является базовым допустим решением
---

[1, 2]: x = [1. 1.] является базовым допустим решением
---

[1, 3]:
Матрица B = [[0. 1.]
 [0. 1.]] вырождена
---

[2, 3]: x = [1. 1.] является базовым допустим решением
---



[array([1., 1.]), array([1., 1.]), array([1., 1.]), array([1., 1.])]

In [5]:
from numpy import dot, array

c = array([-1., -1.])

min_val = 1
x_min = None

for x in bfs:
    val = dot(c, x)

    if val < min_val:
        x_min = x
        min_val = val

print(f'Минимальное значение: {min_val}')

x_min

Минимальное значение: -2.0


array([1., 1.])

In [6]:
from scipy.optimize import linprog

c = [-1., -1.]

bounds = [
    [0., 1.],
    [0., 1.]
]

linprog(c, bounds=bounds)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -2.0
              x: [ 1.000e+00  1.000e+00]
            nit: 0
          lower:  residual: [ 1.000e+00  1.000e+00]
                 marginals: [ 0.000e+00  0.000e+00]
          upper:  residual: [ 0.000e+00  0.000e+00]
                 marginals: [-1.000e+00 -1.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: []
                 marginals: []
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0

### Пример №2:

минимизировать: $$-x_1$$

при условии: $$x_1 + x_2 \leq 1$$
             $$x_1 \leq 1$$
             $$x_2 \leq 1$$
             $$x_1, x_2 \geq 0$$

<center>
    <img src="../images/feasable_set_2.png" width="260">
</center>

<br/>

<center>
    <h3>Стандартная форма</h3>
</center>

минимизировать: $$-x_1$$

при условии: $$x_1 + x_2 + x_3 = 1$$
             $$x_1 + x_4 = 1$$
             $$x_2 + x_5 = 1$$
             $$x_1, x_2, x_3, x_4, x_5 \geq 0$$

<br/>             

$$
    A = \begin{pmatrix}        
        1 & 1 & 1 & 0 & 0 \\
        1 & 0 & 0 & 1 & 0 \\
        0 & 1 & 0 & 0 & 1 \\
    \end{pmatrix},

    b = \begin{pmatrix} 
        1 \\
        1 \\
        1 \\
    \end{pmatrix}
$$

Существует $C_{5}^3 = 10$ базовых допустимых решений             

In [7]:
A = [
    [1., 1., 0.],
    [1., 0., 1.],
    [1., 0., 0.],
    [0., 1., 0.],
    [0., 0., 1.]
]

b = [1., 1., 1.]

bfs = generate_feasable_set(A, b)

bfs

[0, 1, 2]: x = [ 1. -0. -0.] является базовым допустим решением
---

[0, 1, 3]: x = [0. 1. 1.] является базовым допустим решением
---

[0, 1, 4]: x = [0. 1. 1.] является базовым допустим решением
---

[0, 2, 3]:
Матрица B = [[1. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]] вырождена
---

[0, 2, 4]: x = [ 1. -0.  1.] является базовым допустим решением
---

[0, 3, 4]: x = [0. 1. 1.] является базовым допустим решением
---

[1, 2, 3]: x = [ 1.  1. -0.] является базовым допустим решением
---

[1, 2, 4]:
Матрица B = [[1. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]] вырождена
---

[1, 3, 4]: x = [0. 1. 1.] является базовым допустим решением
---

[2, 3, 4]: x = [1. 1. 1.] является базовым допустим решением
---



[array([ 1., -0., -0.]),
 array([0., 1., 1.]),
 array([0., 1., 1.]),
 array([ 1., -0.,  1.]),
 array([0., 1., 1.]),
 array([ 1.,  1., -0.]),
 array([0., 1., 1.]),
 array([1., 1., 1.])]

In [8]:
c = array([-1., 0., 0.])

min_val = 1
x_min = None

for x in bfs:
    val = dot(c, x)

    if val < min_val:
        x_min = x
        min_val = val

print(f'Минимальное значение: {min_val}')

x_min

Минимальное значение: -1.0


array([ 1., -0., -0.])

In [9]:
c = [-1., 0.]

A = [
    [1., 1.]
]

b = [1.]

bounds = [
    [0., 1.],
    [0., 1.]
]

linprog(c, A, b, bounds=bounds)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -1.0
              x: [ 1.000e+00  0.000e+00]
            nit: 0
          lower:  residual: [ 1.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00]
          upper:  residual: [ 0.000e+00  1.000e+00]
                 marginals: [-1.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00]
                 marginals: [-0.000e+00]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0