# Нахождение базовых допустимых решений

In [11]:
import sys

sys.path.append('..')



минимизировать: $$-5x_1 + 4x_2 - 6x_3^+ + 6x_3^-$$

при условии: $$-x_1 +x_2 +s_1 = -7$$
             $$2x_2 - x_3^+ +x_3^- -s_2 = 2$$
             $$x_1 + 2x_3^+ - 2x_3^- =7$$
             $$x_1, x_2, x_3^+, x_3^-,s_1,s_2 \geq 0$$

<br/>

<center>
    <h3>Стандартная форма</h3>
</center>

минимизировать: $$-5x_1 + 4x_2 - 6x_3^+ + 6x_3^- + 0s_1 + 0s_2$$

при условии: $$-x_1 +x_2 +s_1 = -7$$
             $$2x_2 - x_3^+ +x_3^- -s_2 = 2$$
             $$x_1 + 2x_3^+ - 2x_3^- =7$$

<br/>             

$$
    A = \begin{pmatrix}        
        -1 & 1 & 0 & 0 & 1 & 0 \\
        0 & 2 & -1 & 1 & 0 & -1 \\
        1 & 0 & 2 & -2 & 0 & 0 \\
    \end{pmatrix},

    b = \begin{pmatrix} 
        -7 \\
        2 \\
        7 \\
    \end{pmatrix}
$$

In [12]:
from modules.feasable_set import generate_feasable_set

A = [[-1.,   0.,   1.],
    [ 1.,   2.,   0. ],
    [ 0.,  -1.,   2. ],
    [ 0.,   1.,  -2. ],
    [ 1.,   0.,   0. ],
    [ 0.,  -1,  0.]]


b = [-7., 2., 7.]

bfs = generate_feasable_set(A, b)

bfs

[0, 1, 2]: k = 2, x[k] = -0.4 отрицательна
---

[0, 1, 3]: x = [7.8 0.8 0.4] является базовым допустим решением
---

[0, 1, 4]: k = 2, x[k] = -1.0 отрицательна
---

[0, 1, 5]: k = 2, x[k] = -2.0 отрицательна
---

[0, 2, 3]:
Матрица B = [[-1.  0.  1.]
 [ 0. -1.  2.]
 [ 0.  1. -2.]] вырождена
---

[0, 2, 4]: k = 1, x[k] = -2.0 отрицательна
---

[0, 2, 5]: k = 2, x[k] = -2.0 отрицательна
---

[0, 3, 4]: x = [11.  2.  4.] является базовым допустим решением
---

[0, 3, 5]: k = 2, x[k] = -2.0 отрицательна
---

[0, 4, 5]: k = 2, x[k] = -2.0 отрицательна
---

[1, 2, 3]:
Матрица B = [[ 1.  2.  0.]
 [ 0. -1.  2.]
 [ 0.  1. -2.]] вырождена
---

[1, 2, 4]: k = 2, x[k] = -9.75 отрицательна
---

[1, 2, 5]: k = 0, x[k] = -7.0 отрицательна
---

[1, 3, 4]: k = 1, x[k] = -3.5 отрицательна
---

[1, 3, 5]: k = 0, x[k] = -7.0 отрицательна
---

[1, 4, 5]:
Матрица B = [[ 1.  2.  0.]
 [ 1.  0.  0.]
 [ 0. -1.  0.]] вырождена
---

[2, 3, 4]:
Матрица B = [[ 0. -1.  2.]
 [ 0.  1. -2.]
 [ 1.  0.  0.]] вырождена
--

[array([7.8, 0.8, 0. , 0.4, 0. , 0. ]), array([11.,  0.,  0.,  2.,  4.,  0.])]

In [13]:
from numpy import dot, array

c = array([-5, 4, -6, 6, 0, 0])

min_val = 1
x_min = None

for x in bfs:
    val = dot(c, x)

    if val < min_val:
        x_min = x
        min_val = val

print(f'Минимальное значение: {min_val}')

x_min

Минимальное значение: -43.0


array([11.,  0.,  0.,  2.,  4.,  0.])

In [20]:
from scipy.optimize import linprog

c = [-5, 4, -6, 6, 0, 0]
A = [[-1., 1., 0., 0., 1., 0.],
        [0., 2., -1., 1., 0., -.1],
        [1., 0., 2., -2., 0., 0.]]
b =  [-7., 2., 7.]
bounds =  [(0, None), (0, None), (0, None), (0, None), (0, None), (0, None)]

linprog(c, A_eq=A, b_eq=b, bounds=bounds)

       message: The problem is unbounded. (HiGHS Status 10: model_status is Unbounded; primal_status is At upper bound)
       success: False
        status: 3
           fun: None
             x: None
           nit: 4
         lower:  residual: None
                marginals: None
         upper:  residual: None
                marginals: None
         eqlin:  residual: None
                marginals: None
       ineqlin:  residual: None
                marginals: None